### ISSUE TITLE
provide use case

### ISSUE THREAD

**Issue by slachtar** [valentinvichnal/deepstream.io-permission-ratelimiter#1]
Hello,
could you please provide a use case for your plugin.
Thank you

**Comment by valentinvichnal** [comment]
Hello,

Without this plugin if any of your user would write this code in the browser console your server would crash in a few seconds:
```js
while (true) {
  client.rpc.make('comment.create', { commentId: '...', text: '...' }, (error, result) => {})
}
```
The Deepstream server might handle the (100k rpc call/s) but the RPC provider server certainly won't, especially if you do complex or database calls inside the RPC.

Of course DoS WebSocket protection on the network level is better than this plugin, but if you already have that this plugin still can be useful for anti-spam protection.

For example you can config that every user can only comment 10 times every hour.
```js
exports.FREQUENCY = 60 * 60000; // 1 hour
exports.LIMIT = 110;
exports.LIMITS = {
  'default': 1,
  'comment.create': 10,
}
```
Deepstream will reject the 11th call for the `comment.create` RPC for every user in that hour.

DDoS protection only save your server from crashing, this plugin also prevent users to spam your website.

**Comment by slachtar** [comment]
awesome, and very useful, some time ago, I was facing similair issue because of a bad written code client side, which leads to backend server crash (see issue https://github.com/deepstreamIO/deepstream.io/issues/1031), the app was in production and that was very embarrassing, such plugin may have saved my face and prevented crashing, the time I get my code fixed. Of course not to mention that it may prevent attacks and spamming.
I suggest you put your explaination in the README file.
